apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/example-service:latest
  newTag: latest
  # newName: asia.gcr.io/oapi-gateway-sit/direct-credit-on-us
  # newTag: 0df2ca4e