apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/example-service
  newTag: 0f9ef65a


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: example-service-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: example-service-secret-env